(() => {
  const data = window.IPAS_DATA;
  data.pastExams = window.IPAS_PAST_EXAMS || [];
  const storeKey = 'ipas-thomas-progress-v1';
  const colors = { violet:'#7157e8', orange:'#e5894a', blue:'#5283cf', teal:'#2b9b95', pink:'#c46883' };
  const state = { view:'dashboard', level:'初級', quiz:null, quizIndex:0, selected:[], answered:null, dark:localStorage.getItem('ipas-dark') === '1', progress:JSON.parse(localStorage.getItem(storeKey) || '{"answered":[],"mistakes":[],"streak":3}') };
  const app = document.querySelector('#app-view');
  const subject = id => data.subjects.find(item => item.id === id);
  const save = () => localStorage.setItem(storeKey, JSON.stringify(state.progress));
  const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const answeredCount = id => state.progress.answered.filter(qid => data.questions.find(q => q.id === qid)?.subject === id).length;
  const render = () => { document.body.classList.toggle('dark', state.dark); document.querySelector('#mistake-badge').textContent = state.progress.mistakes.length; document.querySelectorAll('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.view === state.view)); if (state.view === 'dashboard') renderDashboard(); if (state.view === 'practice') renderPractice(); if (state.view === 'study') renderStudy(); if (state.view === 'past-exams') renderPastExams(); if (state.view === 'mistakes') renderMistakes(); };
  const renderDashboard = () => {
    const total = data.questions.length, done = state.progress.answered.length, accuracy = done ? Math.round(((done - state.progress.mistakes.length) / done) * 100) : 0;
    app.innerHTML = `<section class="grid dashboard-grid"><div class="hero"><span class="eyebrow">PERSONAL PREP DASHBOARD</span><h2>把每一次練習，變成上場信心。</h2><p>初級與中級分開準備，依照各自學習指引建立專屬練習節奏。</p><div class="hero-actions"><button class="primary-button" data-level="初級" data-view="practice">初級模擬考</button><button class="secondary-button" data-level="中級" data-view="practice">中級模擬考</button></div></div><div class="panel"><div class="panel-header"><h3>本週節奏</h3><span>保持連續</span></div><div class="calendar"><b>一</b><b>二</b><b>三</b><b>四</b><b>五</b><b>六</b><b>日</b>${['done','done','done','done','done','today',''].map((className,index)=>`<span class="day ${className}">${index+3}</span>`).join('')}</div><div class="tip" style="margin-top:18px">小提醒：先用「練習模式」熟悉概念，再用「考試模式」檢查穩定度。</div></div></section><section class="stats"><div class="stat-card"><span class="stat-label">已完成題目</span><div class="stat-value">${done}<small style="font:400 13px 'Noto Sans TC';color:#9ca4b0"> / ${total}</small></div><span class="stat-note">自我檢核題</span></div><div class="stat-card"><span class="stat-label">目前正確率</span><div class="stat-value">${accuracy}%</div><span class="stat-note">依已作答題計算</span></div><div class="stat-card"><span class="stat-label">連續練習</span><div class="stat-value">${state.progress.streak}<small style="font:400 13px 'Noto Sans TC';color:#9ca4b0"> 天</small></div><span class="stat-note">今天再完成一組</span></div></section><section class="grid two-col"><div class="panel"><div class="panel-header"><h3>分級進度</h3><button class="link-button" data-view="study">查看學習地圖 →</button></div><div class="subject-list">${['初級','中級'].map(level=>{const levelQuestions=data.questions.filter(q=>subject(q.subject).level===level);const levelDone=levelQuestions.filter(q=>state.progress.answered.includes(q.id)).length;const pct=levelQuestions.length?Math.round(levelDone/levelQuestions.length*100):0;return `<div class="subject-row"><i class="subject-color" style="background:${level==='初級'?'#7157e8':'#5283cf'}"></i><div class="subject-info"><strong>${level}考試</strong><small>${levelDone} / ${levelQuestions.length} 題已完成</small><div class="progress-track"><div class="progress-bar" style="width:${pct}%;background:${level==='初級'?'#7157e8':'#5283cf'}"></div></div></div><span class="subject-pct">${pct}%</span></div>`}).join('')}</div></div><div class="panel"><div class="panel-header"><h3>今日建議</h3><span>AI Planner focus</span></div><div class="tip" style="background:var(--purple-soft);border-color:#ddd7ff;color:#5b4ac3"><strong>優先複習：AI 風險管理</strong><br />從部署後監控、再訓練與資料治理開始，建立中級科目一的應用脈絡。</div><button class="primary-button" style="margin-top:16px;width:100%" data-start-subject="ai-plan">進入中級科目一</button></div></section>`;
  };
  const renderPractice = () => {
    if (state.quiz) return renderQuiz();
    const levelSubjects=data.subjects.filter(item=>item.level===state.level);
    app.innerHTML = `<div class="view-title"><span class="eyebrow">${state.level.toUpperCase()} PRACTICE ROOM</span><h2>${state.level}考試｜開始一組練習</h2><p>初級與中級題庫分開，現在只會從 ${state.level} 科目取題。</p><div class="hero-actions" style="margin-top:16px"><button class="${state.level==='初級'?'primary-button':'secondary-button'}" data-level="初級" data-view="practice">初級考試</button><button class="${state.level==='中級'?'primary-button':'secondary-button'}" data-level="中級" data-view="practice">中級考試</button></div></div><section class="panel practice-config"><div class="config-block"><label for="question-count">題數</label><input id="question-count" class="number-control" type="number" min="3" max="16" value="8" /><label for="mode" style="margin-top:20px">作答模式</label><select id="mode" class="select-control"><option value="practice">練習模式｜立即看解析</option><option value="exam">考試模式｜最後看結果</option></select></div><div class="config-block"><label>${state.level}練習範圍</label><div class="range-list">${levelSubjects.map(item=>`<label class="range-option"><input type="checkbox" value="${item.id}" checked /><span>${item.level}｜${item.name}</span><small>${data.questions.filter(q=>q.subject===item.id).length} 題</small></label>`).join('')}</div></div></section><div style="display:flex;justify-content:flex-end;margin-top:18px"><button id="start-quiz" class="primary-button">建立${state.level}練習組合 →</button></div>`;
  };
  const renderQuiz = () => {
    const q = state.quiz[state.quizIndex], exam = state.mode === 'exam', subjectInfo = subject(q.subject), currentAnswer = state.answers?.[q.id];
    app.innerHTML = `<div class="quiz-wrap"><div class="quiz-header"><span>${subjectInfo.level}｜${subjectInfo.name}</span><span>${state.quizIndex+1} / ${state.quiz.length}</span></div><div class="progress-track"><div class="progress-bar" style="width:${(state.quizIndex+1)/state.quiz.length*100}%"></div></div><section class="panel" style="margin-top:20px"><span class="tag ${subjectInfo.color !== 'violet' ? subjectInfo.color : ''}">${esc(q.type)} · ${esc(q.chapter)}</span><h2 class="quiz-question">${esc(q.prompt)}</h2><div class="quiz-options">${q.options.map((option,index)=>{let cls='';if(!exam && currentAnswer !== undefined){if(index===q.answer)cls='correct';else if(index===currentAnswer)cls='wrong'}return `<button class="quiz-option ${cls}" data-answer="${index}" ${currentAnswer !== undefined?'disabled':''}><span class="option-letter">${String.fromCharCode(65+index)}</span><span>${esc(option)}</span></button>`}).join('')}</div>${!exam&&currentAnswer!==undefined?`<div class="explanation"><strong>${currentAnswer===q.answer?'回答正確':'再看一次'}</strong><br />${esc(q.explanation)}<br /><small>依據：${esc(q.source)}</small></div>`:''}<div class="quiz-actions"><button class="outline-button" id="quit-quiz">離開練習</button><button class="primary-button" id="next-question" ${currentAnswer===undefined?'disabled':''}>${state.quizIndex===state.quiz.length-1?'查看結果':'下一題 →'}</button></div></section></div>`;
  };
  const renderStudy = () => { app.innerHTML=`<div class="view-title"><span class="eyebrow">STUDY MAP</span><h2>學習地圖</h2><p>依據工作區的 5 份 iPAS 學習指引與勘誤表整理。點開科目即可掌握章節範圍。</p></div><div class="study-grid">${data.subjects.map(item=>`<article class="study-card"><div class="study-card-top"><div><span class="tag ${item.color !== 'violet' ? item.color : ''}">${item.level} · ${item.code}</span><h3>${item.name}</h3></div><span style="font:700 18px 'Space Grotesk';color:${colors[item.color]}">${answeredCount(item.id)}<small style="font:400 10px 'Noto Sans TC';color:var(--muted)"> 題</small></span></div><div class="progress-track"><div class="progress-bar" style="width:${Math.min(100,answeredCount(item.id)/data.questions.filter(q=>q.subject===item.id).length*100)}%;background:${colors[item.color]}"></div></div><ul class="chapter-list">${item.chapters.map(ch=>`<li>${ch}</li>`).join('')}</ul><small style="display:block;color:var(--muted);margin-top:15px;font-size:10px">來源：${item.guide}</small></article>`).join('')}</div>`; };
  const renderPastExams = () => { const grouped = ['初級','中級'].map(level => ({ level, exams:data.pastExams.filter(exam=>exam.level===level) })); app.innerHTML=`<div class="view-title"><span class="eyebrow">PAST EXAM ARCHIVE</span><h2>歷屆考題專區</h2><p>正式歷屆題與學習指引檢核題分開管理；選擇題組後可直接進入考試模式。</p></div><div class="grid two-col">${grouped.map(group=>`<section class="panel"><div class="panel-header"><h3>${group.level}歷屆考題</h3><span>${group.exams.length} 個題組</span></div>${group.exams.length?`<div class="mistake-list">${group.exams.map(exam=>`<div class="mistake-item"><div><strong>${esc(exam.title)}</strong><p>${esc(exam.note||'正式歷屆考題')} · ${exam.questionIds.length} 題</p></div><button class="outline-button" data-past-exam="${esc(exam.id)}">開始考試</button></div>`).join('')}</div>`:`<div class="empty-state"><strong>尚未匯入${group.level}歷屆題目</strong><br /><span>目前工作區只有學習指引與勘誤表，未包含正式歷屆考題檔。</span></div>`}</section>`).join('')}</div><section class="panel" style="margin-top:20px"><div class="panel-header"><h3>匯入規則</h3><span>避免題目來源混淆</span></div><p style="font-size:12px;line-height:1.8;color:var(--muted);margin:0">將正式題目放入 <code>past-exams.js</code> 與題庫資料後，使用 questionIds 對應題目。正式來源、年度與梯次請填入 note 與 title；沒有來源佐證的題目，請維持在一般練習區。</p></section>`; };
  const renderMistakes = () => { const mistakes = state.progress.mistakes.map(id=>data.questions.find(q=>q.id===id)).filter(Boolean); app.innerHTML=`<div class="view-title"><span class="eyebrow">REVIEW LOOP</span><h2>錯題複習</h2><p>把不熟的概念集中處理，完成後會從清單移除。</p></div><section class="panel">${mistakes.length?`<div class="mistake-list">${mistakes.map(q=>`<div class="mistake-item"><div><strong>${esc(q.prompt)}</strong><p>${esc(subject(q.subject).name)} · ${esc(q.chapter)}</p></div><button class="outline-button" data-review="${q.id}">複習</button></div>`).join('')}</div>`:'<div class="empty-state">目前沒有錯題。先完成一組練習，這裡會自動建立你的複習清單。</div>'}</section>`; };
  const startQuiz = ids => { const pool=data.questions.filter(q=>ids.includes(q.subject)); const count=Math.min(Number(document.querySelector('#question-count')?.value||8),pool.length); state.mode=document.querySelector('#mode')?.value||'practice'; state.quiz=[...pool].sort(()=>Math.random()-.5).slice(0,count); state.answers={};state.quizIndex=0;state.view='practice';render(); };
  document.addEventListener('click', event => { const viewButton=event.target.closest('[data-view]'); if(viewButton){if(viewButton.dataset.level)state.level=viewButton.dataset.level;state.view=viewButton.dataset.view;state.quiz=null;document.querySelector('#page-title').textContent=state.view==='dashboard'?'早安，Thomas':({practice:`${state.level}考試`,study:'學習地圖','past-exams':'歷屆考題',mistakes:'錯題複習'}[state.view]||'');render();return} const answer=event.target.closest('[data-answer]');if(answer){const q=state.quiz[state.quizIndex];state.answers[q.id]=Number(answer.dataset.answer);render();return} if(event.target.closest('#start-quiz')){const ids=[...document.querySelectorAll('.range-option input:checked')].map(input=>input.value);if(ids.length)startQuiz(ids);return}if(event.target.closest('[data-past-exam]')){const exam=data.pastExams.find(item=>item.id===event.target.closest('[data-past-exam]').dataset.pastExam);if(exam){state.quiz=exam.questionIds.map(id=>data.questions.find(q=>q.id===id)).filter(Boolean);state.answers={};state.quizIndex=0;state.mode='exam';state.view='practice';render()}return}if(event.target.closest('#next-question')){const q=state.quiz[state.quizIndex];const picked=state.answers[q.id];if(picked===q.answer){state.progress.mistakes=state.progress.mistakes.filter(id=>id!==q.id)}else if(!state.progress.mistakes.includes(q.id))state.progress.mistakes.push(q.id);if(!state.progress.answered.includes(q.id))state.progress.answered.push(q.id);save();if(state.quizIndex===state.quiz.length-1){const total=state.quiz.length,correct=state.quiz.filter(item=>state.answers[item.id]===item.answer).length;state.quiz=null;state.view='dashboard';render();showToast(`完成 ${total} 題，答對 ${correct} 題`)}else{state.quizIndex++;render()}return}if(event.target.closest('#quit-quiz')){state.quiz=null;render();return} const review=event.target.closest('[data-review]');if(review){const q=data.questions.find(item=>item.id===review.dataset.review);state.quiz=[q];state.answers={};state.quizIndex=0;state.mode='practice';state.view='practice';render();return}if(event.target.closest('[data-start-subject]')){state.level='中級';state.view='practice';render();setTimeout(()=>startQuiz(['ai-plan']),0)}});
  document.querySelector('#theme-toggle').addEventListener('click',()=>{state.dark=!state.dark;localStorage.setItem('ipas-dark',state.dark?'1':'0');render()});document.querySelector('#reset-progress').addEventListener('click',()=>{if(confirm('確定要清除本機的作答進度與錯題紀錄嗎？')){state.progress={answered:[],mistakes:[],streak:3};save();render();showToast('進度已重設')}});function showToast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2400)}render();
})();
