/*
 * 官方公告試題匯入區。
 * 題目來源：iPAS 官方公開公告試題 PDF。保留來源網址，方便核對原文。
 * 新增題組時，將題目放入 pastQuestions，再用 questionIds 對應 pastExams。
 */
window.IPAS_PAST_QUESTIONS = [
  { id:'past-115-1-basic-01', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'下列何者不屬於資料整合（Data Integration）的主要目的？', options:['統一不同來源資料的格式與欄位定義，以確保分析一致性','識別並處理重複資料，避免影響模型訓練結果','整併多來源資料，以提升資料完整性與應用價值','依資料保存政策延長原始資料留存期限，以利未來可能的分析需求'], answer:3, explanation:'依官方公告試題答案：D。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-02', subject:'basic-ai', chapter:'人工智慧概念', type:'歷屆考題', prompt:'某智慧城市專案導入 AI 技術，以優化垃圾收集路線調度並即時監測空氣品質變化。系統需持續蒐集環境數據與設備狀態。下列何種技術最直接支援上述需求？', options:['專家系統（Expert System）','決策支援系統（Decision Support System）','啟發式決策引擎（Heuristic Decision Engine）','感知器網路（Sensor Network）'], answer:3, explanation:'依官方公告試題答案：D。感知器網路可持續蒐集環境與設備資料。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-03', subject:'basic-ai', chapter:'機器學習概念', type:'歷屆考題', prompt:'下列何者不符合非監督式學習（Unsupervised Learning）的典型特徵？', options:['模型可依據資料中的特徵相似性進行自動分群','訓練過程中不需仰賴事先定義的標籤資料','常用於探索資料的潛在結構或隱含模式','模型主要學習輸入特徵與既定目標標記之間的對應關係'], answer:3, explanation:'依官方公告試題答案：D。輸入與既定標記的對應關係屬於監督式學習。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-04', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'某保險公司建立 AI 理賠金額預測模型。資料近似常態分佈，但存在少數極端高額案件。下列何者最不適當？', options:['依統計準則（如 Z-score 或 IQR）評估後，再決定是否調整或處理極端值','採用截尾（Trimming）處理極端值，以提升模型穩定性','使用 One-hot 編碼將離群值轉換為類別特徵以改善數值穩定性','結合領域知識評估其合理性，再決定保留或修正'], answer:2, explanation:'依官方公告試題答案：C。One-hot 編碼不是處理數值離群值的適當方法。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-05', subject:'basic-ai', chapter:'機器學習概念', type:'歷屆考題', prompt:'某銀行建立 AI 詐欺交易偵測模型，詐欺樣本比例極低。下列何者最符合 SMOTE 技術的主要功能？', options:['透過隨機刪除部分正常交易資料，以降低類別失衡程度','依據少數類別樣本的特徵空間，合成產生新的少數類別樣本','調整模型的損失函數權重，使誤判少數類別時的懲罰提高','以交叉驗證方式重新分割資料集，使各折資料類別比例一致'], answer:1, explanation:'依官方公告試題答案：B。SMOTE 會在少數類別的特徵空間中合成樣本。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-06', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'為避免資料洩漏，對數值特徵進行標準化時，何者最適當？', options:['資料分割前，先對完整資料集計算統計量並標準化','先分割訓練資料和測試資料，再各自獨立計算統計量','先分割資料，僅以訓練資料計算統計量，再套用至測試資料','僅對訓練資料標準化，測試資料保持原始數值'], answer:2, explanation:'依官方公告試題答案：C。測試資料不能參與訓練階段統計量的計算。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-07', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'為使模型有效使用「資費方案類型」與「客戶地區」等類別型特徵，下列何者最直接？', options:['資料分群（Data Clustering）','特徵交叉（Feature Cross）','One-hot 編碼（One-hot Encoding）','寬深模型（Wide and Deep）'], answer:2, explanation:'依官方公告試題答案：C。One-hot 編碼可將類別型特徵轉為數值格式。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-08', subject:'機器學習概念', type:'歷屆考題', chapter:'機器學習概念', prompt:'大量稀疏類別特徵與數值型特徵並存，且希望學習已出現組合並泛化到未出現組合，最適合哪一種模型架構？', options:['線性迴歸（Linear Regression）','決策樹（Decision Tree）','支援向量機（Support Vector Machine, SVM）','寬深模型（Wide and Deep）'], answer:3, explanation:'依官方公告試題答案：D。Wide and Deep 同時兼顧記憶與泛化。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-09', subject:'basic-ai', chapter:'機器學習概念', type:'歷屆考題', prompt:'神經網路輸出層需要將結果轉換為各類別的機率分佈，最適合使用哪一種函數？', options:['Softmax 函數','Sigmoid 函數','線性函數','ReLU 函數'], answer:0, explanation:'依官方公告試題答案：A。多類別機率分佈常使用 Softmax。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-10', subject:'鑑別式 AI 與生成式 AI 概念', type:'歷屆考題', prompt:'為依據既有圖像資料產生具有變化且風格一致的新圖像，哪一種模型技術最符合需求？', options:['隱變量自編碼器（Variational Autoencoder, VAE）','隨機森林（Random Forest）','K-近鄰演算法（K-Nearest Neighbors, KNN）','貝氏網路（Bayesian Network）'], answer:0, explanation:'依官方公告試題答案：A。VAE 可學習資料的潛在分佈並生成新樣本。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},

  { id:'past-114-2-ai-plan-01', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'企業以自然語言處理分析社群平台與商品評論，以掌握顧客滿意度變化。情感分析模型的主要目的為何？', options:['預測顧客使用的語言風格與語氣','判斷文本中所表達的情感傾向','將顧客留言自動翻譯成指定語言','產生顧客評論的自動化摘要內容'], answer:1, explanation:'依官方公告試題答案：B。情感分析用於判斷文本的情緒或態度傾向。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-02', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'Transformer 架構能改善長篇金融文件的自動翻譯品質，主要原因為何？', options:['透過自注意力機制捕捉長距離語境依賴關係','透過卷積運算加速訓練過程','透過強化學習自動調整語句生成策略','透過資料增強平衡多語語料比例'], answer:0, explanation:'依官方公告試題答案：A。自注意力能處理長距離的上下文關係。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-03', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'BERT 預訓練中的遮罩語言模型（MLM）主要訓練策略為何？', options:['依序遮罩句尾詞語，從左到右逐步生成完整句子','隨機遮罩部分詞語，根據雙向上下文預測被遮罩的詞','以對抗訓練生成語意相似的擾動樣本','以未遮罩的詞為條件，使用解碼器重建整句內容'], answer:1, explanation:'依官方公告試題答案：B。MLM 讓模型利用雙向脈絡預測遮罩詞。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-04', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'GloVe 與 Word2Vec 的主要差異為何？', options:['Word2Vec 以詞頻權重訓練，GloVe 以隨機初始化向量學習','Word2Vec 以全局統計矩陣為基礎，GloVe 採神經網路進行上下文預測','Word2Vec 為基於預測的模型，GloVe 為基於共現統計的模型','Word2Vec 僅能用於靜態文本，GloVe 可應用於即時語料'], answer:2, explanation:'依官方公告試題答案：C。Word2Vec 偏向預測式方法，GloVe 使用全局共現統計。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-05', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'TF-IDF 處理篇幅較長的回饋文本時，可能無法準確反映關鍵詞重要性，主要原因為何？', options:['長文本中的詞頻偏高，導致常見詞權重被過度放大','長文本缺乏明確句子邊界，造成 TF-IDF 無法計算詞頻','TF-IDF 無法同時處理多份文件','長文本會改變 IDF 計算，使所有詞權重趨於相近'], answer:0, explanation:'依官方公告試題答案：A。文本變長可能使詞頻效應放大。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-06', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'N-gram 語言模型生成句子片段合理但整體不連貫，最可能源自哪一項限制？', options:['訓練需要龐大計算量，導致長句無法收斂','僅根據固定長度的前序詞估計機率，難以捕捉長距離依賴','缺乏語意嵌入層，無法表徵詞語間語意相似度','假設詞與詞相互獨立，無法建構上下文關聯'], answer:1, explanation:'依官方公告試題答案：B。固定長度上下文限制了長距離依賴的建模。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-07', subject:'ai-plan', chapter:'電腦視覺技術與應用', type:'歷屆考題', prompt:'物件偵測採用 mAP 評估，IoU 閾值設定較高時代表什麼？', options:['預測邊界框與真實邊界框的重疊程度越高，模型偵測結果越精準','預測邊界框與真實邊界框誤差越大，導致 mAP 上升','模型整體精確率降低但召回率上升','預測邊界框評估不受真實框大小影響'], answer:0, explanation:'依官方公告試題答案：A。較高 IoU 閾值要求更高的框重疊程度。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-08', subject:'ai-plan', chapter:'電腦視覺技術與應用', type:'歷屆考題', prompt:'關於 Softmax 與 Max-Pooling，下列敘述何者正確？', options:['兩者都將特徵張量壓縮為單一最大值','Max-Pooling 會對輸入進行機率分佈轉換','Softmax 保留所有輸入資訊但以比例表示；Max-Pooling 只保留區域最大值','Softmax 主要用於特徵降維，而 Max-Pooling 用於分類輸出'], answer:2, explanation:'依官方公告試題答案：C。Softmax 轉換機率，Max-Pooling 擷取區域最大值。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-09', subject:'ai-plan', chapter:'生成式 AI 技術與應用', type:'歷屆考題', prompt:'生成式 AI 模型導入資料增強後效能下降，何者最可能是原因與改善策略？', options:['增強樣本未經隨機初始化，應重新設計訓練啟動流程','增強後資料的特徵分佈與原始資料不一致，應檢查並調整增強策略以維持語意一致性','增強樣本比例過高，應提高增強比例並調整學習率','增強後資料標註可信度下降，應改用半監督學習重新校正'], answer:1, explanation:'依官方公告試題答案：B。資料增強須維持與原始任務一致的資料分佈與語意。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-10', subject:'ai-plan', chapter:'模型訓練、評估與驗證', type:'歷屆考題', prompt:'若希望同時兼顧精確率（Precision）與召回率（Recall），哪一個指標可作為綜合評估標準？', options:['準確率（Accuracy）','均方根誤差（RMSE）','均方誤差（MSE）','F1 分數（F1 Score）'], answer:3, explanation:'依官方公告試題答案：D。F1 是 Precision 與 Recall 的調和平均。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'}
];

window.IPAS_PAST_QUESTIONS.push(
  { id:'past-115-1-gen-ai-01', subject:'gen-ai', chapter:'生成式 AI 導入評估規劃', type:'歷屆考題', prompt:'生成式 AI 商品推薦在不同客戶族群出現難以解釋的差異，若要優先降低模型偏差風險，何者最合理？', options:['重新檢視訓練資料的樣本分布與代表性','限制推薦結果僅顯示高銷量商品','降低模型參數規模以簡化決策邏輯','提高推薦結果的隨機性以增加多樣性'], answer:0, explanation:'依官方公告試題答案：A。先檢視資料代表性與分布，是處理偏差風險的基本步驟。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-02', subject:'gen-ai', chapter:'生成式 AI 應用領域與工具使用', type:'歷屆考題', prompt:'企業 GPU 與記憶體受限，想以參數高效微調技術降低需更新的參數數量，何者最適合？', options:['知識蒸餾','提示詞工程','梯度凍結','低秩適配（LoRA）'], answer:3, explanation:'依官方公告試題答案：D。LoRA 以低秩矩陣近似更新，能減少可訓練參數。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-03', subject:'gen-ai', chapter:'No code / Low code 概念', type:'歷屆考題', prompt:'Low-Code 儀表板需支援即時監控，且特別關注穩定性與分析可信度，最應優先確認什麼？', options:['穩定的資料串接能力與即時更新機制','自動化決策建議與預測分析模組','彈性介面設計與多角色權限管理','流程觸發與跨系統通知功能'], answer:0, explanation:'依官方公告試題答案：A。資料串接與更新穩定性是即時分析可信度的基礎。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-04', subject:'gen-ai', chapter:'生成式 AI 應用領域與工具使用', type:'歷屆考題', prompt:'生成式 AI 客服系統吞吐量正常，但使用者感覺單次回覆卡頓，應優先進行哪一種效能測試？', options:['評估系統長時間運作的穩定程度','測量系統單位時間的總處理量','比較不同回覆內容的語言品質','分析單次互動回覆的反應速度表現'], answer:3, explanation:'依官方公告試題答案：D。題目描述的是單次互動延遲，應觀察回應時間。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-05', subject:'gen-ai', chapter:'生成式 AI 技術與應用', type:'歷屆考題', prompt:'系統要理解完整語句、維持長對話上下文一致性，何種模型架構較適合？', options:['卷積神經網路（CNN）','遞迴神經網路（RNN）','基於 Transformer 的自迴歸模型','生成對抗網路（GAN）'], answer:2, explanation:'依官方公告試題答案：C。Transformer 自迴歸模型適合長脈絡的序列生成。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-06', subject:'gen-ai', chapter:'AI 風險與治理', type:'歷屆考題', prompt:'下列何者不屬於 OpenAI 官方為 Sora 內容提供的出處證明工具？', options:['資產內嵌的 C2PA 元數據','預設可見的動態浮水印','用於追蹤生成內容的內部反向影像與音訊搜尋工具','平台對外開放的即時來源驗證介面'], answer:3, explanation:'依官方公告試題答案：D。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-07', subject:'gen-ai', chapter:'No code / Low code 概念', type:'歷屆考題', prompt:'No-Code／Low-Code 平台擴大使用後，從資料治理觀點看，何者最合理？', options:['平台內建角色權限與資料存取控管，有助治理制度落實','平台強化自主性，通常使既有治理流程難以延續','資料治理仍需完全仰賴外部系統','自動化設定可顯著降低治理與合規管理需求'], answer:0, explanation:'依官方公告試題答案：A。內建權限與存取控管可支援治理落實。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-08', subject:'gen-ai', chapter:'生成式 AI 導入評估規劃', type:'歷屆考題', prompt:'同一即時監控應用在雲端順暢，部署到邊緣裝置後延遲與效能下降，最合理的解釋是？', options:['邊緣運算可降低系統對效能的需求','No-Code／Low-Code 平台只能在雲端執行','雲端部署通常比邊緣部署更容易出現延遲','邊緣裝置通常受限於運算能力與可用資源'], answer:3, explanation:'依官方公告試題答案：D。邊緣設備的計算資源通常較受限。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-09', subject:'gen-ai', chapter:'提示工程、RAG 與 Agent', type:'歷屆考題', prompt:'Few-shot Prompting 套用到新市場後分類不穩定，原範例未涵蓋新市場表達方式，主要原因是？', options:['模型容易對單一範例產生過度記憶','少量範例難以涵蓋新情境的資料差異','Prompt 無法引導模型擷取共通特徵','模型推理能力不足以完成分類'], answer:1, explanation:'依官方公告試題答案：B。少量範例的代表性不足，無法覆蓋新情境。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},
  { id:'past-115-1-gen-ai-10', subject:'gen-ai', chapter:'提示工程、RAG 與 Agent', type:'歷屆考題', prompt:'RAG 系統品質穩定但延遲與成本增加，採用知識蒸餾最合理的作法是？', options:['將檢索資料轉為結構化規則取代模型','增加檢索文件數量改善效能','停用生成模型避免延遲','使小型模型學習大型模型行為，以降低推論成本'], answer:3, explanation:'依官方公告試題答案：D。知識蒸餾可讓較小模型學習教師模型行為。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 2'},

  { id:'past-114-2-big-data-01', subject:'big-data', chapter:'敘述性統計與資料摘要技術', type:'歷屆考題', prompt:'某數據點的 Z 分數為 2，代表什麼意涵？', options:['原始數值為 2','比平均值低 2 個標準差','代表數據為異常值','比平均值高 2 個標準差'], answer:3, explanation:'依官方公告試題答案：D。Z=2 表示高於平均值 2 個標準差。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-02', subject:'big-data', chapter:'敘述性統計與資料摘要技術', type:'歷屆考題', prompt:'使用 pandas 計算「總銷售額」欄位的平均值、標準差等敘述性統計量，應使用哪一種語法？', options:["df['總銷售額'].sum()","df['總銷售額'].describe()","df['總銷售額'].sort_values()","df['總銷售額'].stats()"], answer:1, explanation:'依官方公告試題答案：B。describe() 會提供多項敘述性統計量。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-03', subject:'big-data', chapter:'機率分佈與資料分佈模型', type:'歷屆考題', prompt:'題目所示分佈圖的偏態（Skewness）值較有可能為哪一個選項？', options:['Skewness < 0','Skewness > 0','Skewness = 0','無法計算 Skewness'], answer:0, explanation:'依官方公告試題答案：A。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-04', subject:'big-data', chapter:'機率分佈與資料分佈模型', type:'歷屆考題', prompt:'累積分佈函數（CDF）的數學定義為何？', options:['機率密度函數的平均值','機率密度函數的積分','機率密度函數的離散總和','機率密度函數的標準差'], answer:1, explanation:'依官方公告試題答案：B。CDF 是 PDF 從負無限到指定值的累積積分。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-05', subject:'big-data', chapter:'數據收集與清理', type:'歷屆考題', prompt:'使用 Label Encoding 將類別變數轉為數字，最常見的潛在風險是什麼？', options:['無法處理缺值','引入類別之間的虛假順序關係','無法擴展至新資料','記憶體佔用過高'], answer:1, explanation:'依官方公告試題答案：B。無序類別被編成數字後，模型可能誤認大小關係。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-06', subject:'big-data', chapter:'數據處理技術與工具', type:'歷屆考題', prompt:'下列關於類別型與數值型資料處理的敘述，何者不正確？', options:['One-Hot 適用於無序類別，但高基數可能造成維度爆炸','Label Encoding 用於無序資料可能導致模型誤解數值大小','Standardization 會使平均值為 0、標準差為 1，且同時將範圍壓縮至 0 至 1','連續變數分箱可提升可解釋性，但可能造成資訊損失'], answer:2, explanation:'依官方公告試題答案：C。Standardization 不保證將數值範圍壓縮至 0 至 1。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-07', subject:'big-data', chapter:'數據儲存與管理', type:'歷屆考題', prompt:'資料庫 ACID 特性中的原子性（Atomicity）是什麼？', options:['所有資料欄位必須為相同型別','每次交易需以批次方式執行','交易不可分割，需完全成功或完全失敗','系統自動同步交易資料至所有節點'], answer:2, explanation:'依官方公告試題答案：C。原子性要求交易不可被拆分成部分成功。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-08', subject:'big-data', chapter:'數據處理技術與工具', type:'歷屆考題', prompt:'以銷售金額與瀏覽次數計算「銷售金額／瀏覽次數」新變數，屬於哪一種特徵工程方法？', options:['特徵選擇','特徵衍生','特徵轉換','分箱處理'], answer:1, explanation:'依官方公告試題答案：B。利用既有欄位計算新欄位屬於特徵衍生。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-09', subject:'big-data', chapter:'數據處理技術與工具', type:'歷屆考題', prompt:'數值特徵存在極端值時，哪一種縮放方法最適合？', options:['Min-Max 正規化','Z-score 標準化','穩健縮放（Robust Scaling）','標準分箱'], answer:2, explanation:'依官方公告試題答案：C。Robust Scaling 對離群值較不敏感。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},
  { id:'past-114-2-big-data-10', subject:'big-data', chapter:'常見的大數據分析方法', type:'歷屆考題', prompt:'哪一種情境最適合應用異常偵測？', options:['根據歷史銷售預測旺季供貨短缺','以信用風險模型預測違約','即時分析金融交易流，偵測與平常行為明顯不同的交易','監控登入次數並預測次日登入量'], answer:2, explanation:'依官方公告試題答案：C。異常偵測用於辨識偏離正常模式的事件。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 2'},

  { id:'past-115-1-ml-01', subject:'ml', chapter:'機率／統計之機器學習基礎應用', type:'歷屆考題', prompt:'以大量隨機市場情境估算投資組合損失分布，屬於哪一種技術框架？', options:['馬可夫鏈','梯度下降最佳化','蒙地卡羅方法','貝氏推論'], answer:2, explanation:'依官方公告試題答案：C。蒙地卡羅方法以大量隨機抽樣近似結果。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-02', subject:'ml', chapter:'模型訓練、評估與驗證', type:'歷屆考題', prompt:'若要讓模型對少數豪宅的極端預測誤差更敏感，應優先選擇哪一種損失函數？', options:['平均絕對誤差（MAE）','Huber 損失','均方誤差（MSE）','交叉熵損失'], answer:2, explanation:'依官方公告試題答案：C。MSE 對大誤差施加平方懲罰。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-03', subject:'ml', chapter:'深度學習原理與框架', type:'歷屆考題', prompt:'Q 形狀為（1,10）、WQ 形狀為（10,64），執行 Q × WQ 後輸出形狀為何？', options:['（1,64）','（10,10）','（64,1）','維度不相容，無法相乘'], answer:0, explanation:'依官方公告試題答案：A。矩陣乘法結果為 1 × 64。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-04', subject:'ml', chapter:'數據準備與特徵工程', type:'歷屆考題', prompt:'隨機水平翻轉的資料擴增最可能對哪一項任務造成語意錯誤？', options:['寵物監控中的貓狗分類','車輛辨識中的車型分類','手寫數字辨識','道路場景中的行人偵測'], answer:2, explanation:'依官方公告試題答案：C。某些手寫數字水平翻轉後可能對應不同數字標籤。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-05', subject:'ml', chapter:'模型訓練、評估與驗證', type:'歷屆考題', prompt:'殘差隨預測值增大而呈現擴散現象，最可能代表什麼問題？', options:['殘差之間存在關聯','特徵之間高度相關','殘差變異數不一致','殘差不符合常態分布'], answer:2, explanation:'依官方公告試題答案：C。擴散形狀常表示異質變異。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-06', subject:'ml', chapter:'數值優化技術與方法', type:'歷屆考題', prompt:'關於 t-SNE 與 PCA 的選型，何者最正確？', options:['t-SNE 保留全局線性結構，適合作為 XGBoost 前處理','t-SNE 保留局部鄰域結構，適合視覺化，但不適合作為模型輸入特徵','PCA 為非線性降維方法，能保留複雜流形結構','t-SNE 與 PCA 皆可直接對新資料進行線性外推'], answer:1, explanation:'依官方公告試題答案：B。t-SNE 偏重局部鄰域視覺化，PCA 才是線性降維。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-07', subject:'ml', chapter:'模型調整與優化', type:'歷屆考題', prompt:'高度相關特徵在每次重新訓練後重要性清單反覆變動，最可能的原因是？', options:['L2 正則化將所有係數壓縮至接近零','L1 正則化面對高度相關特徵時可能不穩定地保留其中之一','未使用正則化，係數每次收斂到不同極值','特徵過多導致梯度消失'], answer:1, explanation:'依官方公告試題答案：B。L1 在高度相關特徵間可能任意選擇代表特徵。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-08', subject:'ml', chapter:'數值優化技術與方法', type:'歷屆考題', prompt:'學習率過大最直接導致哪一種現象？', options:['梯度消失','損失函數震盪或發散','過擬合','死亡 ReLU'], answer:1, explanation:'依官方公告試題答案：B。更新步伐過大會在最優點兩側跳越。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-09', subject:'ml', chapter:'數值優化技術與方法', type:'歷屆考題', prompt:'Adam 能改善訓練震盪與收斂速度的主要原因為何？', options:['結合一階動量與自適應學習率，為每個參數調整更新步長','強制所有參數使用相同學習率','透過批次正規化重新分布輸入資料','將梯度裁剪為固定範圍'], answer:0, explanation:'依官方公告試題答案：A。Adam 結合動量與參數個別的自適應步長。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'},
  { id:'past-115-1-ml-10', subject:'ml', chapter:'模型訓練、評估與驗證', type:'歷屆考題', prompt:'預測隔日使用時長與隔日是否流失，應分別選擇哪種損失函數？', options:['使用時長：MSE；流失：二元交叉熵','使用時長：交叉熵；流失：MSE','使用時長：Hinge；流失：MAE','兩個任務均使用交叉熵'], answer:0, explanation:'依官方公告試題答案：A。連續值回歸常用 MSE，二元分類常用二元交叉熵。', source:'iPAS 官方公告試題｜115 年第 1 次中級科目 3'}
);

window.IPAS_PAST_EXAMS = [
  { id:'past-115-1-basic-subject-1', level:'初級', title:'115 年第 1 次｜初級科目 1：人工智慧基礎概論', year:'115', note:'考試日期：115 年 03 月 21 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/115%E5%B9%B4%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%88%9D%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB_%E7%AC%AC%E4%B8%80%E7%A7%91_%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E5%9F%BA%E7%A4%8E%E6%A6%82%E8%AB%96_%E5%85%AC%E5%91%8A%E8%A9%A6%E9%A1%8C_20260410164304.pdf', questionIds:['past-115-1-basic-01','past-115-1-basic-02','past-115-1-basic-03','past-115-1-basic-04','past-115-1-basic-05','past-115-1-basic-06','past-115-1-basic-07','past-115-1-basic-08','past-115-1-basic-09','past-115-1-basic-10'] },
  { id:'past-114-2-ai-plan-subject-1', level:'中級', title:'114 年第 2 次｜中級科目 1：人工智慧技術應用與規劃', year:'114', note:'考試日期：114 年 11 月 08 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/114%E5%B9%B4%E7%AC%AC%E4%BA%8C%E6%A2%AF%E6%AC%A1%E4%B8%AD%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB%E7%AC%AC%E4%B8%80%E7%A7%91%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E6%8A%80%E8%A1%93%E6%87%89%E7%94%A8%E8%88%87%E8%A6%8F%E5%8A%83%28%E7%95%B6%E6%AC%A1%E8%A9%A6%E9%A1%8C%E5%85%AC%E5%91%8A114_20251226000616.pdf', questionIds:['past-114-2-ai-plan-01','past-114-2-ai-plan-02','past-114-2-ai-plan-03','past-114-2-ai-plan-04','past-114-2-ai-plan-05','past-114-2-ai-plan-06','past-114-2-ai-plan-07','past-114-2-ai-plan-08','past-114-2-ai-plan-09','past-114-2-ai-plan-10'] }
  ,{ id:'past-115-1-gen-ai-subject-2', level:'初級', title:'115 年第 1 次｜初級科目 2：生成式 AI 應用與規劃', year:'115', note:'考試日期：115 年 03 月 21 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/115%E5%B9%B4%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%88%9D%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB_%E7%AC%AC%E4%BA%8C%E7%A7%91_%E7%94%9F%E6%88%90%E5%BC%8FAI%E6%87%89%E7%94%A8%E8%88%87%E8%A6%8F%E5%8A%83_%E5%85%AC%E5%91%8A%E8%A9%A6%E9%A1%8C_20260410164328.pdf', questionIds:['past-115-1-gen-ai-01','past-115-1-gen-ai-02','past-115-1-gen-ai-03','past-115-1-gen-ai-04','past-115-1-gen-ai-05','past-115-1-gen-ai-06','past-115-1-gen-ai-07','past-115-1-gen-ai-08','past-115-1-gen-ai-09','past-115-1-gen-ai-10'] },
  { id:'past-114-2-big-data-subject-2', level:'中級', title:'114 年第 2 次｜中級科目 2：大數據處理分析與應用', year:'114', note:'考試日期：114 年 11 月 08 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/114%E5%B9%B4%E7%AC%AC%E4%BA%8C%E6%A2%AF%E6%AC%A1%E4%B8%AD%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB%E7%AC%AC%E4%BA%8C%E7%A7%91%E5%A4%A7%E6%95%B8%E6%93%9A%E8%99%95%E7%90%86%E5%88%86%E6%9E%90%E8%88%87%E6%87%89%E7%94%A8%28%E7%95%B6%E6%AC%A1%E8%A9%A6%E9%A1%8C%E5%85%AC%E5%91%8A114_20251226000634.pdf', questionIds:['past-114-2-big-data-01','past-114-2-big-data-02','past-114-2-big-data-03','past-114-2-big-data-04','past-114-2-big-data-05','past-114-2-big-data-06','past-114-2-big-data-07','past-114-2-big-data-08','past-114-2-big-data-09','past-114-2-big-data-10'] },
  { id:'past-115-1-ml-subject-3', level:'中級', title:'115 年第 1 次｜中級科目 3：機器學習技術與應用', year:'115', note:'考試日期：115 年 05 月 23 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/115%E5%B9%B4%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%B8%AD%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB_%E7%AC%AC%E4%B8%89%E7%A7%91_%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92%E6%8A%80%E8%A1%93%E8%88%87%E6%87%89%E7%94%A8_%E5%85%AC%E5%91%8A%E8%A9%A6%E9%A1%8C_20260615003428.pdf', questionIds:['past-115-1-ml-01','past-115-1-ml-02','past-115-1-ml-03','past-115-1-ml-04','past-115-1-ml-05','past-115-1-ml-06','past-115-1-ml-07','past-115-1-ml-08','past-115-1-ml-09','past-115-1-ml-10'] }
];

window.IPAS_DATA.questions.push(...window.IPAS_PAST_QUESTIONS);
