/*
 * 官方公告試題匯入區。
 * 題目來源：iPAS 官方公開公告試題 PDF。保留來源網址，方便核對原文。
 * 新增題組時，將題目放入 pastQuestions，再用 questionIds 對應 pastExams。
 */
window.IPAS_PAST_QUESTIONS = [
  { id:'past-115-1-basic-01', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'下列何者不屬於資料整合（Data Integration）的主要目的？', options:['統一不同來源資料的格式與欄位定義，以確保分析一致性','識別並處理重複資料，避免影響模型訓練結果','整併多來源資料，以提升資料完整性與應用價值','依資料保存政策延長原始資料留存期限，以利未來可能的分析需求'], answer:3, explanation:'依官方公告試題答案：D。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-02', subject:'basic-ai', chapter:'人工智慧概念', type:'歷屆考題', prompt:'某智慧城市專案導入 AI 技術，以優化垃圾收集路線調度並即時監測空氣品質變化。系統需持續蒐集環境數據與設備狀態。下列何種技術最直接支援上述需求？', options:['專家系統（Expert System）','決策支援系統（Decision Support System）','啟發式決策引擎（Heuristic Decision Engine）','感知器網路（Sensor Network）'], answer:3, explanation:'依官方公告試題答案：D。感知器網路可持續蒐集環境與設備資料。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-03', subject:'basic-ai', chapter:'機器學習概念', type:'歷屆考題', prompt:'下列何者不符合非監督式學習（Unsupervised Learning）的典型特徵？', options:['模型可依據資料中的特徵相似性進行自動分群','訓練過程中不需仰賴事先定義的標籤資料','常用於探索資料的潛在結構或隱含模式','模型主要學習輸入特徵與既定目標標記之間的對應關係'], answer:3, explanation:'依官方公告試題答案：D。輸入與既定標記的對應關係屬於監督式學習。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-04', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'某保險公司建立 AI 理賠金額預測模型。資料近似常態分佈，但存在少數極端高額案件。下列何者最不適當？', options:['依統計準則（如 Z-score 或 IQR）評估後，再決定是否調整或處理極端值','採用截尾（Trimming）處理極端值，以提升模型穩定性','使用 One-hot 編碼將離群值轉換為類別特徵以改善數值穩定性','結合領域知識評估其合理性，再決定保留或修正'], answer:2, explanation:'依官方公告試題答案：C。One-hot 編碼不是處理數值離群值的適當方法。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-05', subject:'basic-ai', chapter:'機器學習概念', type:'歷屆考題', prompt:'某銀行建立 AI 詐欺交易偵測模型，詐欺樣本比例極低。下列何者最符合 SMOTE 技術的主要功能？', options:['透過隨機刪除部分正常交易資料，以降低類別失衡程度','依據少數類別樣本的特徵空間，合成產生新的少數類別樣本','調整模型的損失函數權重，使誤判少數類別時的懲罰提高','以交叉驗證方式重新分割資料集，使各折資料類別比例一致'], answer:1, explanation:'依官方公告試題答案：B。SMOTE 會在少數類別的特徵空間中合成樣本。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-06', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'為避免資料洩漏，對數值特徵進行標準化時，何者最適當？', options:['資料分割前，先對完整資料集計算統計量並標準化','先分割訓練資料和測試資料，再各自獨立計算統計量','先分割資料，僅以訓練資料計算統計量，再套用至測試資料','僅對訓練資料標準化，測試資料保持原始數值'], answer:2, explanation:'依官方公告試題答案：C。測試資料不能參與訓練階段統計量的計算。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-07', subject:'basic-ai', chapter:'資料處理與分析概念', type:'歷屆考題', prompt:'為使模型有效使用「資費方案類型」與「客戶地區」等類別型特徵，下列何者最直接？', options:['資料分群（Data Clustering）','特徵交叉（Feature Cross）','One-hot 編碼（One-hot Encoding）','寬深模型（Wide and Deep）'], answer:2, explanation:'依官方公告試題答案：C。One-hot 編碼可將類別型特徵轉為數值格式。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-08', subject:'機器學習概念', type:'歷屆考題', chapter:'機器學習概念', prompt:'大量稀疏類別特徵與數值型特徵並存，且希望學習已出現組合並泛化到未出現組合，最適合哪一種模型架構？', options:['線性迴歸（Linear Regression）','決策樹（Decision Tree）','支援向量機（Support Vector Machine, SVM）','寬深模型（Wide and Deep）'], answer:3, explanation:'依官方公告試題答案：D。Wide and Deep 同時兼顧記憶與泛化。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-09', subject:'basic-ai', chapter:'機器學習概念', type:'歷屆考題', prompt:'神經網路輸出層需要將結果轉換為各類別的機率分佈，最適合使用哪一種函數？', options:['Softmax 函數','Sigmoid 函數','線性函數','ReLU 函數'], answer:0, explanation:'依官方公告試題答案：A。多類別機率分佈常使用 Softmax。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},
  { id:'past-115-1-basic-10', subject:'鑑別式 AI 與生成式 AI 概念', type:'歷屆考題', prompt:'為依據既有圖像資料產生具有變化且風格一致的新圖像，哪一種模型技術最符合需求？', options:['隱變量自編碼器（Variational Autoencoder, VAE）','隨機森林（Random Forest）','K-近鄰演算法（K-Nearest Neighbors, KNN）','貝氏網路（Bayesian Network）'], answer:0, explanation:'依官方公告試題答案：A。VAE 可學習資料的潛在分佈並生成新樣本。', source:'iPAS 官方公告試題｜115 年第 1 次初級科目 1'},

  { id:'past-114-2-ai-plan-01', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'企業以自然語言處理分析社群平台與商品評論，以掌握顧客滿意度變化。情感分析模型的主要目的為何？', options:['預測顧客使用的語言風格與語氣','判斷文本中所表達的情感傾向','將顧客留言自動翻譯成指定語言','產生顧客評論的自動化摘要內容'], answer:1, explanation:'依官方公告試題答案：B。情感分析用於判斷文本的情緒或態度傾向。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-02', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'Transformer 架構能改善長篇金融文件的自動翻譯品質，主要原因為何？', options:['透過自注意力機制捕捉長距離語境依賴關係','透過卷積運算加速訓練過程','透過強化學習自動調整語句生成策略','透過資料增強平衡多語語料比例'], answer:0, explanation:'依官方公告試題答案：A。自注意力能處理長距離的上下文關係。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-03', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'BERT 預訓練中的遮罩語言模型（MLM）主要訓練策略為何？', options:['依序遮罩句尾詞語，從左到右逐步生成完整句子','隨機遮罩部分詞語，根據雙向上下文預測被遮罩的詞','以對抗訓練生成語意相似的擾動樣本','以未遮罩的詞為條件，使用解碼器重建整句內容'], answer:1, explanation:'依官方公告試題答案：B。MLM 讓模型利用雙向脈絡預測遮罩詞。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-04', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'GloVe 與 Word2Vec 的主要差異為何？', options:['Word2Vec 以詞頻權重訓練，GloVe 以隨機初始化向量學習','Word2Vec 以全局統計矩陣為基礎，GloVe 採神經網路進行上下文預測','Word2Vec 為基於預測的模型，GloVe 為基於共現統計的模型','Word2Vec 僅能用於靜態文本，GloVe 可應用於即時語料'], answer:2, explanation:'依官方公告試題答案：C。Word2Vec 偏向預測式方法，GloVe 使用全局共現統計。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-05', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'TF-IDF 處理篇幅較長的回饋文本時，可能無法準確反映關鍵詞重要性，主要原因為何？', options:['長文本中的詞頻偏高，導致常見詞權重被過度放大','長文本缺乏明確句子邊界，造成 TF-IDF 無法計算詞頻','TF-IDF 無法同時處理多份文件','長文本會改變 IDF 計算，使所有詞權重趨於相近'], answer:0, explanation:'依官方公告試題答案：A。文本變長可能使詞頻效應放大。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-06', subject:'ai-plan', chapter:'自然語言處理技術與應用', type:'歷屆考題', prompt:'N-gram 語言模型生成句子片段合理但整體不連貫，最可能源自哪一項限制？', options:['訓練需要龐大計算量，導致長句無法收斂','僅根據固定長度的前序詞估計機率，難以捕捉長距離依賴','缺乏語意嵌入層，無法表徵詞語間語意相似度','假設詞與詞相互獨立，無法建構上下文關聯'], answer:1, explanation:'依官方公告試題答案：B。固定長度上下文限制了長距離依賴的建模。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-07', subject:'ai-plan', chapter:'電腦視覺技術與應用', type:'歷屆考題', prompt:'物件偵測採用 mAP 評估，IoU 閾值設定較高時代表什麼？', options:['預測邊界框與真實邊界框的重疊程度越高，模型偵測結果越精準','預測邊界框與真實邊界框誤差越大，導致 mAP 上升','模型整體精確率降低但召回率上升','預測邊界框評估不受真實框大小影響'], answer:0, explanation:'依官方公告試題答案：A。較高 IoU 閾值要求更高的框重疊程度。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-08', subject:'ai-plan', chapter:'電腦視覺技術與應用', type:'歷屆考題', prompt:'關於 Softmax 與 Max-Pooling，下列敘述何者正確？', options:['兩者都將特徵張量壓縮為單一最大值','Max-Pooling 會對輸入進行機率分佈轉換','Softmax 保留所有輸入資訊但以比例表示；Max-Pooling 只保留區域最大值','Softmax 主要用於特徵降維，而 Max-Pooling 用於分類輸出'], answer:2, explanation:'依官方公告試題答案：C。Softmax 轉換機率，Max-Pooling 擷取區域最大值。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-09', subject:'ai-plan', chapter:'生成式 AI 技術與應用', type:'歷屆考題', prompt:'生成式 AI 模型導入資料增強後效能下降，何者最可能是原因與改善策略？', options:['增強樣本未經隨機初始化，應重新設計訓練啟動流程','增強後資料的特徵分佈與原始資料不一致，應檢查並調整增強策略以維持語意一致性','增強樣本比例過高，應提高增強比例並調整學習率','增強後資料標註可信度下降，應改用半監督學習重新校正'], answer:1, explanation:'依官方公告試題答案：B。資料增強須維持與原始任務一致的資料分佈與語意。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'},
  { id:'past-114-2-ai-plan-10', subject:'ai-plan', chapter:'模型訓練、評估與驗證', type:'歷屆考題', prompt:'若希望同時兼顧精確率（Precision）與召回率（Recall），哪一個指標可作為綜合評估標準？', options:['準確率（Accuracy）','均方根誤差（RMSE）','均方誤差（MSE）','F1 分數（F1 Score）'], answer:3, explanation:'依官方公告試題答案：D。F1 是 Precision 與 Recall 的調和平均。', source:'iPAS 官方公告試題｜114 年第 2 次中級科目 1'}
];

window.IPAS_PAST_EXAMS = [
  { id:'past-115-1-basic-subject-1', level:'初級', title:'115 年第 1 次｜初級科目 1：人工智慧基礎概論', year:'115', note:'考試日期：115 年 03 月 21 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/115%E5%B9%B4%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%88%9D%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB_%E7%AC%AC%E4%B8%80%E7%A7%91_%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E5%9F%BA%E7%A4%8E%E6%A6%82%E8%AB%96_%E5%85%AC%E5%91%8A%E8%A9%A6%E9%A1%8C_20260410164304.pdf', questionIds:['past-115-1-basic-01','past-115-1-basic-02','past-115-1-basic-03','past-115-1-basic-04','past-115-1-basic-05','past-115-1-basic-06','past-115-1-basic-07','past-115-1-basic-08','past-115-1-basic-09','past-115-1-basic-10'] },
  { id:'past-114-2-ai-plan-subject-1', level:'中級', title:'114 年第 2 次｜中級科目 1：人工智慧技術應用與規劃', year:'114', note:'考試日期：114 年 11 月 08 日｜官方公告試題', sourceUrl:'https://www.ipas.org.tw/api/proxy/uploads/certification_resource/bf93f438f7be48d295c1b40a34d79f3d/114%E5%B9%B4%E7%AC%AC%E4%BA%8C%E6%A2%AF%E6%AC%A1%E4%B8%AD%E7%B4%9AAI%E6%87%89%E7%94%A8%E8%A6%8F%E5%8A%83%E5%B8%AB%E7%AC%AC%E4%B8%80%E7%A7%91%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E6%8A%80%E8%A1%93%E6%87%89%E7%94%A8%E8%88%87%E8%A6%8F%E5%8A%83%28%E7%95%B6%E6%AC%A1%E8%A9%A6%E9%A1%8C%E5%85%AC%E5%91%8A114_20251226000616.pdf', questionIds:['past-114-2-ai-plan-01','past-114-2-ai-plan-02','past-114-2-ai-plan-03','past-114-2-ai-plan-04','past-114-2-ai-plan-05','past-114-2-ai-plan-06','past-114-2-ai-plan-07','past-114-2-ai-plan-08','past-114-2-ai-plan-09','past-114-2-ai-plan-10'] }
];

window.IPAS_DATA.questions.push(...window.IPAS_PAST_QUESTIONS);
